server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # 필요에 따라 create, update, validate 등으로 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySQL 전용 Dialect 설정
        format_sql: true

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}