server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_NAME}

  jpa:
    hibernate:
      ddl-auto: none # 필요에 따라 create, update, validate 등으로 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySQL 전용 Dialect 설정
        format_sql: true

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}
